In [4]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler 
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd 
import tensorflow as tf

2023-05-08 18:50:33.965879: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
df= pd.read_csv('data/10tomaspordatoduplicadas-17-apr-2023.csv', sep=',',names=["FechaHora", "NumPaquete", "IdClient", "ax","ay","az","gx","gy","gz","Actividad"])  
df

FechaHora  NumPaquete  IdClient      ax      ay      az  \
0     Mon Apr 17 21:16:34 2023         0.0       0.0 -7386.0  -774.0  1236.0   
1     Mon Apr 17 21:16:34 2023         1.0       0.0 -7296.0 -1046.0  1390.0   
2     Mon Apr 17 21:16:34 2023         2.0       0.0 -7370.0 -1150.0  1588.0   
3     Mon Apr 17 21:16:34 2023         3.0       0.0 -7494.0 -1212.0  1820.0   
4     Mon Apr 17 21:16:34 2023         4.0       0.0 -7566.0 -1248.0  1996.0   
...                        ...         ...       ...     ...     ...     ...   
6273  Mon Apr 17 21:18:15 2023      6273.0       0.0 -7610.0  1378.0 -1006.0   
6274  Mon Apr 17 21:18:15 2023      6274.0       0.0 -7688.0  1872.0 -1336.0   
6275  Mon Apr 17 21:18:15 2023      6275.0       0.0 -8234.0  1694.0 -1870.0   
6276  Mon Apr 17 21:18:15 2023      6276.0       0.0 -8402.0  1420.0 -2032.0   
6277  Mon Apr 17 21:18:15 2023      6277.0       0.0 -8084.0   950.0 -1626.0   

          gx      gy      gz  Actividad  
0    -3434.0 -1935.0   -25.0          2  
1    -3709.0 -1647.0   -14.0          2  
2    -3753.0 -1455.0  -178.0          2  
3    -3532.0 -1772.0  -286.0          2  
4    -3053.0 -2183.0  -365.0          2  
...      ...     ...     ...        ...  
6273  1799.0  -242.0  -996.0          1  
6274  1824.0  -469.0 -1755.0          1  
6275   980.0  -671.0 -1074.0          1  
6276   -59.0   231.0  -266.0          1  
6277  -355.0  1049.0    48.0          1  

[6278 rows x 10 columns]

In [6]:
df.max()

FechaHora     Mon Apr 17 21:18:15 2023
NumPaquete                      6277.0
IdClient                           0.0
ax                             32767.0
ay                             27410.0
az                             27626.0
gx                             32767.0
gy                             32767.0
gz                             32767.0
Actividad                            2
dtype: object

## Normalization

In [7]:
# The acelerometer goes between -4g and +4g and the equivalent LSB is 8192
df['ax']= df['ax']/8192
df['ay']= df['ay']/8192
df['az']= df['az']/8192


# The gyroscope goes between -500 and 500 and the equivalent LSB is 65.5
df['gx']= df['gx']/65.5
df['gy']= df['gy']/65.5
df['gz']= df['gz']/65.5
df.max()

FechaHora     Mon Apr 17 21:18:15 2023
NumPaquete                      6277.0
IdClient                           0.0
ax                            3.999878
ay                            3.345947
az                            3.372314
gx                          500.259542
gy                          500.259542
gz                          500.259542
Actividad                            2
dtype: object

In [8]:
#After scalating the values we normalize
#Aceleromter
df['ax']=(df['ax'] - df['ax'].min()) / (df['ax'].max() - df['ax'].min())
df['ay']=(df['ay'] - df['ay'].min()) / (df['ay'].max() - df['ay'].min())
df['az']=(df['az'] - df['az'].min()) / (df['az'].max() - df['az'].min())
#Gyroscope
df['gx']=(df['gx'] - df['gx'].min()) / (df['gx'].max() - df['gx'].min())
df['gy']=(df['gy'] - df['gy'].min()) / (df['gy'].max() - df['gy'].min())
df['gz']=(df['gz'] - df['gz'].min()) / (df['gz'].max() - df['gz'].min())

df.max()

FechaHora     Mon Apr 17 21:18:15 2023
NumPaquete                      6277.0
IdClient                           0.0
ax                                 1.0
ay                                 1.0
az                                 1.0
gx                                 1.0
gy                                 1.0
gz                                 1.0
Actividad                            2
dtype: object

In [9]:
df

FechaHora  NumPaquete  IdClient        ax        ay  \
0     Mon Apr 17 21:16:34 2023         0.0       0.0  0.387304  0.531656   
1     Mon Apr 17 21:16:34 2023         1.0       0.0  0.388678  0.527136   
2     Mon Apr 17 21:16:34 2023         2.0       0.0  0.387549  0.525408   
3     Mon Apr 17 21:16:34 2023         3.0       0.0  0.385657  0.524378   
4     Mon Apr 17 21:16:34 2023         4.0       0.0  0.384558  0.523779   
...                        ...         ...       ...       ...       ...   
6273  Mon Apr 17 21:18:15 2023      6273.0       0.0  0.383886  0.567417   
6274  Mon Apr 17 21:18:15 2023      6274.0       0.0  0.382696  0.575626   
6275  Mon Apr 17 21:18:15 2023      6275.0       0.0  0.374365  0.572668   
6276  Mon Apr 17 21:18:15 2023      6276.0       0.0  0.371801  0.568115   
6277  Mon Apr 17 21:18:15 2023      6277.0       0.0  0.376654  0.560304   

            az        gx        gy        gz  Actividad  
0     0.563036  0.447608  0.470481  0.499626          2  
1     0.565586  0.443412  0.474876  0.499794          2  
2     0.568864  0.442741  0.477806  0.497292          2  
3     0.572706  0.446113  0.472969  0.495644          2  
4     0.575620  0.453422  0.466697  0.494438          2  
...        ...       ...       ...       ...        ...  
6273  0.525913  0.527459  0.496315  0.484810          1  
6274  0.520449  0.527840  0.492851  0.473228          1  
6275  0.511607  0.514961  0.489769  0.483619          1  
6276  0.508925  0.499107  0.503532  0.495949          1  
6277  0.515647  0.494591  0.516014  0.500740          1  

[6278 rows x 10 columns]

In [10]:
df.groupby('Actividad').count()

FechaHora  NumPaquete  IdClient    ax    ay    az    gx    gy    gz
Actividad                                                                     
0               2011        2011      2011  2011  2011  2011  2011  2011  2011
1               1893        1893      1893  1893  1893  1893  1893  1893  1893
2               2374        2374      2374  2374  2374  2374  2374  2374  2374

## Separating x and y

In [11]:
X=df.iloc[:,3:9].values
y=pd.get_dummies(df.iloc[:,-1].values)
y=np.array(y)
print(X)
print(y)
print(X.shape)
print(y.shape)

[[0.38730449 0.53165609 0.56303606 0.44760815 0.47048142 0.49962615]
 [0.38867781 0.52713616 0.56558599 0.44341192 0.47487602 0.499794  ]
 [0.38754864 0.52540796 0.56886446 0.44274052 0.47780575 0.49729152]
 ...
 [0.37436484 0.57266775 0.51160711 0.51496147 0.48976883 0.48361944]
 [0.37180133 0.56811459 0.50892473 0.49910735 0.50353246 0.49594873]
 [0.3766537  0.56030443 0.51564725 0.49459068 0.51601434 0.50074006]]
[[0 0 1]
 [0 0 1]
 [0 0 1]
 ...
 [0 1 0]
 [0 1 0]
 [0 1 0]]
(6278, 6)
(6278, 3)


## Train and test split

In [12]:
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size=0.2, random_state=23)

#Creating the neural network 

In [13]:
# build the model and train it
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(50, activation='relu')) # relu is used for performance
model.add(tf.keras.layers.Dense(15, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax')) # softmax is used, because we only expect one gesture to occur per input
model.compile(optimizer='rmsprop', loss='mse', metrics=['mae','accuracy'])
history = model.fit(X_train, y_train, epochs=100, batch_size=1)

Epoch 1/100


2023-05-08 18:50:49.849281: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


5022/5022 [==============================] - 4s 689us/step - loss: 0.1786 - mae: 0.3746 - accuracy: 0.5876
Epoch 2/100
5022/5022 [==============================] - 4s 724us/step - loss: 0.1270 - mae: 0.2666 - accuracy: 0.7047
Epoch 3/100
5022/5022 [==============================] - 4s 710us/step - loss: 0.1135 - mae: 0.2309 - accuracy: 0.7352
Epoch 4/100
5022/5022 [==============================] - 3s 657us/step - loss: 0.1048 - mae: 0.2142 - accuracy: 0.7545
Epoch 5/100
5022/5022 [==============================] - 3s 679us/step - loss: 0.0980 - mae: 0.2020 - accuracy: 0.7684
Epoch 6/100
5022/5022 [==============================] - 3s 653us/step - loss: 0.0915 - mae: 0.1893 - accuracy: 0.7806
Epoch 7/100
5022/5022 [==============================] - 3s 680us/step - loss: 0.0885 - mae: 0.1826 - accuracy: 0.7865
Epoch 8/100
5022/5022 [==============================] - 3s 681us/step - loss: 0.0858 - mae: 0.1745 - accuracy: 0.7939
Epoch 9/100
5022/5022 [==============================] - 3s 

In [20]:
# use the model to predict the test inputs
y_pred = model.predict(X_test)

# print the predictions and the expected ouputs
print("predictions =\n", np.round(y_pred, decimals=3))
print("actual =\n", y_test)
print(X_test.shape)
print(y_pred.shape)

40/40 [==============================] - 0s 605us/step
predictions =
 [[0.785 0.    0.215]
 [0.827 0.002 0.171]
 [1.    0.    0.   ]
 ...
 [0.931 0.069 0.   ]
 [0.    0.002 0.998]
 [0.438 0.539 0.023]]
actual =
 [[1 0 0]
 [1 0 0]
 [1 0 0]
 ...
 [1 0 0]
 [0 0 1]
 [1 0 0]]
(1256, 6)
(1256, 3)


In [21]:
#Transforming y pred to 1 and 0
y_pred=(y_pred == y_pred.max(axis=1, keepdims=1)).astype(float)
print("predictions =\n", np.round(y_pred, decimals=3))
print("actual =\n", y_test)

predictions =
 [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
actual =
 [[1 0 0]
 [1 0 0]
 [1 0 0]
 ...
 [1 0 0]
 [0 0 1]
 [1 0 0]]


In [22]:
def undecode(twodimesnional_array):
    decoded_array=np.zeros(twodimesnional_array.shape[0])
    #print(decoded_array)
    cont=0
    for row in twodimesnional_array:
        #print(row)
        for i in range(len(row)):
            if row[i]==1.0:
                decoded_array[cont]=int(i)
        #print(decoded_array[cont])
        cont=cont+1
   
    return decoded_array

In [23]:
y_pred_decoded=undecode(y_pred)
print(y_pred_decoded)

[0. 0. 0. ... 0. 2. 1.]


In [24]:
y_test_undecoded=undecode(y_test)
print(y_test_undecoded)

[0. 0. 0. ... 0. 2. 0.]


In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test_undecoded, y_pred_decoded)
print(cm)
accuracy_score(y_test_undecoded, y_pred_decoded)

[[310   3  79]
 [  6 404   4]
 [ 43   8 399]]


0.8861464968152867

 # Generate a TensorFlow Lite Model

In [27]:
# Convert the model to the TensorFlow Lite format without quantization
converter = tf.lite.TFLiteConverter.from_keras_model(model)
model_no_quant_tflite = converter.convert()

# Save the model to disk
open("converted_model_noquant.tflite", "wb").write(model_no_quant_tflite)

# Convert the model to the TensorFlow Lite format with quantization
#def representative_dataset():
#  for i in range(500):
#    yield([x_train[i].reshape(1, 1)])
# Set the optimization flag.
#converter.optimizations = [tf.lite.Optimize.DEFAULT]
# Enforce integer only quantization
#converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
#converter.inference_input_type = tf.int8
#converter.inference_output_type = tf.int8
# Provide a representative dataset to ensure we quantize correctly.
#converter.representative_dataset = representative_dataset
#model_tflite = converter.convert()

# Save the model to disk
#open("esp_split1/converted_model_split1.tflite", "wb").write(model_tflite)

2023-05-08 19:26:07.638649: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2023-05-08 19:26:07.638733: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2023-05-08 19:26:07.653827: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:364] Ignored output_format.
2023-05-08 19:26:07.653848: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
2023-05-08 19:26:07.662678: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:2116] Estimated count of arithmetic ops: 2450  ops, equivalently 1225  MACs


6516

# To convert to C++
We can then run this command to convert the model to c code.

xxd -i converted_model.tflite > model_data.cc